### ISSUE TITLE
DB Connection timeout crashes App

### ISSUE THREAD

**Issue by t3patterson** [muktek/homepage#2]
```
017-08-02T23:23:50.145414+00:00 app[web.1]: events.js:182
2017-08-02T23:23:50.145428+00:00 app[web.1]:       throw er; // Unhandled 'error' event
2017-08-02T23:23:50.145428+00:00 app[web.1]:       ^
2017-08-02T23:23:50.145429+00:00 app[web.1]: 
2017-08-02T23:23:50.145430+00:00 app[web.1]: Error: connection timeout
2017-08-02T23:23:50.145431+00:00 app[web.1]:     at Db.<anonymous> (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:169:17)
2017-08-02T23:23:50.145432+00:00 app[web.1]:     at emitTwo (events.js:125:13)
2017-08-02T23:23:50.145432+00:00 app[web.1]:     at Db.emit (events.js:213:7)
2017-08-02T23:23:50.145433+00:00 app[web.1]:     at Server.listener (/app/node_modules/mongodb/lib/db.js:1798:14)
2017-08-02T23:23:50.145434+00:00 app[web.1]:     at emitOne (events.js:115:13)
2017-08-02T23:23:50.145434+00:00 app[web.1]:     at Server.emit (events.js:210:7)
2017-08-02T23:23:50.145434+00:00 app[web.1]:     at Server.<anonymous> (/app/node_modules/mongodb/lib/server.js:274:14)
2017-08-02T23:23:50.145435+00:00 app[web.1]:     at emitOne (events.js:115:13)
2017-08-02T23:23:50.145435+00:00 app[web.1]:     at Server.emit (events.js:210:7)
2017-08-02T23:23:50.145436+00:00 app[web.1]:     at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:335:12)
2017-08-02T23:23:50.145436+00:00 app[web.1]:     at emitOne (events.js:115:13)
2017-08-02T23:23:50.145436+00:00 app[web.1]:     at Pool.emit (events.js:210:7)
2017-08-02T23:23:50.145437+00:00 app[web.1]:     at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:270:12)
2017-08-02T23:23:50.145437+00:00 app[web.1]:     at Object.onceWrapper (events.js:318:30)
2017-08-02T23:23:50.145437+00:00 app[web.1]:     at emitTwo (events.js:125:13)
2017-08-02T23:23:50.145438+00:00 app[web.1]:     at Connection.emit (events.js:213:7)
2017-08-02T23:23:50.145438+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:185:10)
2017-08-02T23:23:50.145439+00:00 app[web.1]:     at Object.onceWrapper (events.js:314:30)
2017-08-02T23:23:50.145439+00:00 app[web.1]:     at emitNone (events.js:105:13)
2017-08-02T23:23:50.145439+00:00 app[web.1]:     at Socket.emit (events.js:207:7)
2017-08-02T23:23:50.145440+00:00 app[web.1]:     at Socket._onTimeout (net.js:402:8)
2017-08-02T23:23:50.145440+00:00 app[web.1]:     at ontimeout (timers.js:469:11)
2017-08-02T23:23:50.269177+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2017-08-02T23:23:50.269336+00:00 app[web.1]: npm ERR! errno 1
2017-08-02T23:23:50.269447+00:00 app[web.1]: npm ERR! muktekhome@1.0.0 start: `node --use_strict server.js`
2017-08-02T23:23:50.269531+00:00 app[web.1]: npm ERR! Exit status 1
2017-08-02T23:23:50.269632+00:00 app[web.1]: npm ERR! 
2017-08-02T23:23:50.269723+00:00 app[web.1]: npm ERR! Failed at the muktekhome@1.0.0 start script.
2017-08-02T23:23:50.269810+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2017-08-02T23:23:50.276559+00:00 app[web.1]: 
2017-08-02T23:23:50.276698+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2017-08-02T23:23:50.276775+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2017-08-02T23_23_50_254Z-debug.log
2017-08-02T23:23:50.355596+00:00 heroku[web.1]: State changed from up to crashed
2017-08-02T23:23:50.357944+00:00 heroku[web.1]: State changed from crashed to starting
```

**Comment by t3patterson** [comment]
changed db connection tries + interval in configuration for `db-connect.js`

```js
{
	server: {
		reconnectTries: 1000,
		reconnectInterval: 1000
	}
}
```
